image : microsoft/dotnet:latest
stages:
  - build
before_script:
  - 'dotnet restore'
build:
 stage: build
 script:
  - 'dotnet build -c Release -f netcoreapp1.0 '
#  - 'dotnet pack -c Release sly/sly.csproj'
 artifacts:
  paths:
  - sly/bin/Release/netcoreapp1.0/
  - expressionParser/bin/Release/netcoreapp1.0/
  - jsonparser/bin/Release/netcoreapp1.0/
  - sly/bin/Release/*.nupkg
 