image : microsoft/dotnet:latest
stages:
  - build
before_script:
  - 'dotnet restore'
build:
 stage: build
 script:
  - 'dotnet build -c Release'
 artifacts:
  paths:
  - sly/bin/Release/netcoreapp1.0/*.*
 only:
   - master