version: 1.0.{build}
branches:
  only:
  - dev
  - master
image: Previous Visual Studio 2017
build_script:
- cmd: >-
    uname -a

    dotnet restore

    dotnet build -c Release

    dotnet test -f netcoreapp1.0 ParserTests/ParserTests.csproj

    dotnet pack -c Release
test: off
artifacts:
- path: sly/bin/release/*
  name: sly
notifications:
- provider: Email
  to:
  - olivier.duhart@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
