version: 1.0.{build}
branches:
  only:
  - dev
image: Previous Visual Studio 2017
build_script:
- cmd: >-
    uname -a

    dotnet restore

    dotnet build -c Release

    dotnet test -f netcoreapp1.0 ParserTests/ParserTests.csproj

    dotnet pack -c Release
test: off
artifacts:
- path: sly/bin/release/*
  name: sly