version: 1.0.{build}
image: Visual Studio 2017
init:
- cmd: >-
    choco install opencover.portable

    choco install codecov
environment:
  nugetKey:
    secure: c1PEIupjD4bY0aJ2UYpyhayC+2VAC/5zxCzOi2dIEhKATogvn5Hlv98I9RhBPuF9
  codecovToken:
    secure: tDNSMb2HRVQsJEgwVvuqY02+qgaKI3bw0LHSqplQKSPSRJNEkdCVnX352HoSht5t
build_script:
- ps: "dotnet --info\nAdd-AppveyorMessage \"build started\"\nWrite-Host \"restoring nugets\"\ndotnet restore\nAdd-AppveyorMessage \"nugets restored\"\nWrite-Host \"building solution (Release)\"\ndotnet build -c Release\nAdd-AppveyorMessage \"dotnet build success\"\nWrite-Host \"running XUnit tests and coverage\"\n\nOpenCover.Console.exe -excludebyattribute:*.ExcludeFromCoverage* -register:user -target:\"c:\\Program Files\\dotnet\\dotnet.exe\" -targetargs:\"test --logger:trx;LogFileName=results.trx /p:DebugType=full ParserTests/ParserTests.csproj\"  -output:\".\\sly_coverage.xml\" -oldStyle -filter:\"+[sly*]* -[ParserTests*]* -[samples*]*\"\ncodecov -t 0777b110-895e-466f-ad53-a0e04860c4ee -f sly_coverage.xml /p:DebugType=full \n\nAdd-AppveyorMessage \"xunit tests done\"\nWrite-Host \"packing nuget\"\ndotnet pack -c Release\nAdd-AppveyorMessage \"sly nuget packaged\""
test_script:
- ps: dotnet test ParserTests/ParserTests.csproj
artifacts:
- path: sly/bin/release/*
  name: sly
- path: sly_coverage.xml
  name: sly
deploy:
- provider: NuGet
  api_key:
    secure: c1PEIupjD4bY0aJ2UYpyhayC+2VAC/5zxCzOi2dIEhKATogvn5Hlv98I9RhBPuF9
  skip_symbols: true
  on:
    branch: dev
notifications:
- provider: Email
  to:
  - olivier.duhart@gmail.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
